sources: 
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: nations
      - name: regions
      - name: v_nations  
      - name: orders 
      - name: lineitems
      - name: parts

      - name: suppliers
        config:
          freshness:
            warn_after: {count: 1, period: hour}
            error_after: {count: 1, period: hour}
          loaded_at_field: o_orderdate::timestamp_ntz

  - name: src2
    database: MKMOTORS_DEV
    schema: STAGING
    tables:
      - name: stg_employees

  - name: src3
    database: analytics
    schema: dbt_ssv
    tables:
      - name: suppliers